# Maven
- task: AzureAppServiceManage@0
  inputs:
    azureSubscription: 'Azure for Students(2e3f618e-ef76-457e-98e1-57e41c74bd15)'
    Action: 'Swap Slots'
    WebAppName: 'azure-arm'
    ResourceGroupName: 'Azure-Training'
    PreserveVnet: true
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
